export type LocalItemProperty={id:number;name:string;value:string;unit:string;quantity:number|null;relationKind:"none"|"item"|"creature";relatedName:string;notes:string};
export type LocalItemEffect={id:number;effect:string;amount:number|null;application:string;conditionName:string;duration:string;durationCount:number|null;label:string;channel:string;attribute:string;skillId:number|null;movementMode:string;title:string;requiredEquipmentState:string;passive:boolean;lifecycle:string;instructions:string};
export type LocalItemPower={id:number;name:string;trigger:string;resolutionMode:string;resourceCost:string;resourceAmount:number|null;fixedRollTarget:number|null;magic:string;powerLevel:number|null;description:string};
export type LocalFiringMode={id:number;name:string;cyclingInitiativeCost:number|null;recoilResetInitiativeCost:number|null;deliveryCadence:string;roundsPerCadence:number|null};
export type LocalWeaponProfile={profileRecordType:string;weaponType:string;handedness:string;damageSource:string;damage:number|null;damageType:string;initiativeCost:number|null;rangeMode:string;distanceUnit:string;reach:number|null;shortRange:number|null;mediumRange:number|null;longRange:number|null;rateOfFire:string;reloadType:string;capacityRounds:number|null;drawInitiative:number|null;unloadInitiative:number|null;changeModeInitiative:number|null;cyclingInitiativeModifier:number|null;recoilResetInitiativeModifier:number|null;compatibility:string;weaponRules:string;ammunitionItemName:string;firingModes:LocalFiringMode[]};
export type LocalMagazineProfile={capacityRounds:number;fillInitiativeCostPerRound:number|null;ammunitionNames:string[]};
export type LocalArmorProfile={armorType:string;baseSoak:number|null;coverage:string;damageModifierSource:string;armorRules:string};
export type LocalItem={
 id:number;scope:"equipment"|"inventory";isMagical:boolean;name:string;canonicalId:string;equipmentGroup:string|null;recordType:string;family:string;category:string;subtype:string;description:string;weight:number|null;weightUnit:string;size:string;durability:number|null;credits:number|null;priceBasis:string;
 useMode:"none"|"consume-item"|"charges"|"unlimited";activationLabel:string;quantityPerUse:number|null;maximumCharges:number|null;chargesPerUse:number|null;rechargeNotes:string;useNotes:string;
 properties:LocalItemProperty[];effects:LocalItemEffect[];powers:LocalItemPower[];weaponProfile:LocalWeaponProfile|null;magazineProfile:LocalMagazineProfile|null;armorProfile:LocalArmorProfile|null;tags:Array<{id:number;group:string;tag:string}>;variants:Array<{id:number;name:string;notes:string}>;
 archivedAt:string|null;archiveReason:string;createdAt:string;updatedAt:string;
};
export const EQUIPMENT_KEY="serrian-tide:prototype:equipment:v2";
export const INVENTORY_KEY="serrian-tide:prototype:inventory:v2";
export function itemKey(scope:"equipment"|"inventory"){return scope==="equipment"?EQUIPMENT_KEY:INVENTORY_KEY}
export function readItems(scope:"equipment"|"inventory"):LocalItem[]{if(typeof window==="undefined")return[];try{const p=JSON.parse(localStorage.getItem(itemKey(scope))??"[]");return Array.isArray(p)?p:[]}catch{return[]}}
export function writeItems(scope:"equipment"|"inventory",rows:LocalItem[]){localStorage.setItem(itemKey(scope),JSON.stringify(rows))}
export function blankItem(scope:"equipment"|"inventory"):LocalItem{const now=new Date().toISOString();return{id:0,scope,isMagical:false,name:"",canonicalId:"",equipmentGroup:scope==="equipment"?"general":null,recordType:scope==="equipment"?"Equipment":"Item",family:scope==="equipment"?"General Equipment":"General Inventory",category:"General",subtype:"",description:"",weight:null,weightUnit:"",size:"",durability:null,credits:null,priceBasis:"per item",useMode:"none",activationLabel:"",quantityPerUse:null,maximumCharges:null,chargesPerUse:null,rechargeNotes:"",useNotes:"",properties:[],effects:[],powers:[],weaponProfile:null,magazineProfile:null,armorProfile:null,tags:[],variants:[],archivedAt:null,archiveReason:"",createdAt:now,updatedAt:now}}
export function blankWeapon():LocalWeaponProfile{return{profileRecordType:"weapon",weaponType:"",handedness:"",damageSource:"weapon",damage:null,damageType:"",initiativeCost:null,rangeMode:"",distanceUnit:"",reach:null,shortRange:null,mediumRange:null,longRange:null,rateOfFire:"",reloadType:"",capacityRounds:null,drawInitiative:null,unloadInitiative:null,changeModeInitiative:null,cyclingInitiativeModifier:null,recoilResetInitiativeModifier:null,compatibility:"",weaponRules:"",ammunitionItemName:"",firingModes:[]}}
