export const CREATURE_STORAGE_KEY="serrian-tide:prototype:creatures:v2";
export type LocalCreatureMovement={id:number;mode:string;baseValue:number;notes:string};
export type LocalHitLocation={id:number;roll:number|null;locationName:string;bodyParts:string;hpPool:string;naturalArmor:string;soak:number|null;locationEffect:string};
export type LocalCreatureAttack={id:number;name:string;attackPercent:number|null;damage:number|null;damageType:string;rangeReach:string;requiredAnatomy:string;usesRecharge:string;requirements:string;specialEffect:string;notes:string};
export type LocalCreatureSkill={skillId:number;skillName:string;classification:string;rank:number|null;notes:string};
export type LocalCreatureAbility={id:number;name:string;type:string;activation:string;crImpact:string;usesRecharge:string;requirements:string;description:string;mechanicalNotes:string;notes:string};
export type LocalCreatureDefense={id:number;defenseType:string;against:string;value:string;crImpact:string;notes:string};
export type LocalCreatureUse={id:number;name:string;notes:string};
export type LocalCreatureVariant={id:number;name:string;notes:string};
export type LocalCreature={id:number;canonicalName:string;family:string;creatureType:string;size:string;derivedFrom:string;description:string;typicalBehavior:string;habitatEcology:string;notes:string;attributes:Record<"STR"|"DEX"|"CON"|"INT"|"WIS"|"CHR",number>;hpMultiplierSteps:number;baseMovementSteps:number;baseMagicSteps:number;totalHp:number|null;movement:LocalCreatureMovement[];hitLocations:LocalHitLocation[];attacks:LocalCreatureAttack[];skills:LocalCreatureSkill[];abilities:LocalCreatureAbility[];defenses:LocalCreatureDefense[];uses:LocalCreatureUse[];manualCrAdjustment:number;adjustmentReason:string;challengeRating:number;calculatedChallengeRating:number;killXp:number;variants:LocalCreatureVariant[];archivedAt:string|null;archiveReason:string;createdAt:string;updatedAt:string};
export function readCreatures():LocalCreature[]{if(typeof window==="undefined")return[];try{const p=JSON.parse(localStorage.getItem(CREATURE_STORAGE_KEY)??"[]");return Array.isArray(p)?p:[]}catch{return[]}}
export function writeCreatures(rows:LocalCreature[]){localStorage.setItem(CREATURE_STORAGE_KEY,JSON.stringify(rows))}
export function blankCreature():LocalCreature{const now=new Date().toISOString();return{id:0,canonicalName:"",family:"",creatureType:"",size:"Medium",derivedFrom:"",description:"",typicalBehavior:"",habitatEcology:"",notes:"",attributes:{STR:0,DEX:0,CON:0,INT:0,WIS:0,CHR:0},hpMultiplierSteps:0,baseMovementSteps:0,baseMagicSteps:0,totalHp:null,movement:[],hitLocations:[],attacks:[],skills:[],abilities:[],defenses:[],uses:[],manualCrAdjustment:0,adjustmentReason:"",challengeRating:1,calculatedChallengeRating:1,killXp:0,variants:[],archivedAt:null,archiveReason:"",createdAt:now,updatedAt:now}}
