"use client";
import Link from "next/link";
import { useMemo,useState } from "react";
import { readNpcs,writeNpcs,type LocalNpc } from "@/lib/local-npc-store";
import "../npcs.css";
export function LocalNpcDetail({npcId}:{npcId:number}){
 const initial=useMemo(()=>readNpcs().find(n=>n.id===npcId)??null,[npcId]);const [draft,setDraft]=useState<LocalNpc|null>(initial);const [dirty,setDirty]=useState(false);
 if(!draft)return <main className="npcs-page"><div className="npcs-empty"><h2>NPC not found.</h2><Link href="/heavens/npcs">Back</Link></div></main>;
 function change(update:Partial<LocalNpc>){setDraft(d=>d?{...d,...update}:d);setDirty(true)}
 function save(){const rows=readNpcs();const i=rows.findIndex(n=>n.id===draft.id);if(i<0)return;rows[i]={...draft,updatedAt:new Date().toISOString()};writeNpcs(rows);setDraft(rows[i]!);setDirty(false)}
 const attrs=Object.keys(draft.attributes) as Array<keyof LocalNpc["attributes"]>;
 return <main className="npcs-page"><header className="npcs-header"><Link href="/heavens" className="font-portcullion npcs-logo">Serrian<br/>Tide</Link><div><p>THE HEAVENS / NPCS / DETAILED</p><h1>{draft.name}</h1><span>{draft.sourceName} · {dirty?"Unsaved changes":"Saved locally"}</span></div><nav><Link href="/heavens/npcs">← NPC Archive</Link></nav></header><section className="npcs-simple-editor"><header><div><p>DETAILED NPC RECORD</p><h2>{draft.name}</h2><span>No live runtime fields are included.</span></div><button onClick={save}>Save</button></header><div className="npcs-form-grid"><label><span>Name</span><input value={draft.name} onChange={e=>change({name:e.target.value})}/></label><label><span>Role / Label</span><input value={draft.roleLabel} onChange={e=>change({roleLabel:e.target.value})}/></label>{attrs.map(k=><label key={k}><span>{k}</span><input type="number" value={draft.attributes[k]} onChange={e=>change({attributes:{...draft.attributes,[k]:Number(e.target.value)}})}/></label>)}<label className="is-wide"><span>Personality</span><textarea rows={4} value={draft.personality} onChange={e=>change({personality:e.target.value})}/></label><label className="is-wide"><span>Goals</span><textarea rows={4} value={draft.goals} onChange={e=>change({goals:e.target.value})}/></label><label className="is-wide"><span>Secrets</span><textarea rows={4} value={draft.secrets} onChange={e=>change({secrets:e.target.value})}/></label><label className="is-wide"><span>Backstory</span><textarea rows={6} value={draft.backstory} onChange={e=>change({backstory:e.target.value})}/></label><label className="is-wide"><span>Motivations</span><textarea rows={4} value={draft.motivations} onChange={e=>change({motivations:e.target.value})}/></label><label className="is-wide"><span>Notes</span><textarea rows={4} value={draft.notes} onChange={e=>change({notes:e.target.value})}/></label></div></section></main>;
}
