"use client";
import Link from "next/link";
import { useMemo,useState } from "react";
import { readSkills } from "@/lib/local-skill-store";
import { blankDerivedAbility,readDerivedAbilities,writeDerivedAbilities,type LocalDerivedAbility,type LocalRequirement,type LocalCondition,type LocalCost,type LocalEffect } from "@/lib/local-derived-store";
import "../skills/skills.css";
import "./derived-abilities.css";

type Tab="definition"|"requirements"|"conditions"|"costs"|"limits"|"effects"|"preview";
const TABS:[Tab,string][]=[["definition","Definition"],["requirements","Requirements"],["conditions","Use Conditions"],["costs","Costs"],["limits","Limits & Recharge"],["effects","Mechanical Effects"],["preview","Preview"]];
const ATTRS=["STR","DEX","CON","INT","WIS","CHR"];
function Field({label,children,wide=false,help}:{label:string;children:React.ReactNode;wide?:boolean;help?:string}){return <label className={wide?"derived-ability-field is-wide":"derived-ability-field"}><span>{label}</span>{children}{help?<small>{help}</small>:null}</label>}

export default function DerivedAbilitiesPage(){
 const [version,setVersion]=useState(0),[life,setLife]=useState<"active"|"archived">("active"),[search,setSearch]=useState(""),[acq,setAcq]=useState(""),[act,setAct]=useState("");
 const [draft,setDraft]=useState<LocalDerivedAbility>(()=>blankDerivedAbility()),[dirty,setDirty]=useState(false),[tab,setTab]=useState<Tab>("definition"),[feedback,setFeedback]=useState("");
 const skills=useMemo(()=>readSkills().filter(s=>!s.archivedAt),[version]);const abilities=useMemo(()=>{void version;return readDerivedAbilities()},[version]);
 const visible=abilities.filter(a=>Boolean(a.archivedAt)===(life==="archived")).filter(a=>!search.trim()||[a.name,a.description,a.rulesText].some(v=>v.toLowerCase().includes(search.trim().toLowerCase()))).filter(a=>!acq||a.acquisitionType===acq).filter(a=>!act||a.activationType===act).sort((a,b)=>a.name.localeCompare(b.name));
 function change(u:Partial<LocalDerivedAbility>){setDraft(d=>({...d,...u}));setDirty(true);setFeedback("")}
 function fresh(){if(dirty&&!confirm("Discard unsaved Derived Ability changes?"))return;setDraft(blankDerivedAbility());setDirty(false);setTab("definition");setLife("active")}
 function open(a:LocalDerivedAbility){if(dirty&&!confirm("Discard unsaved Derived Ability changes?"))return;setDraft(a);setDirty(false);setTab("definition")}
 function save(){if(!draft.name.trim()){setFeedback("Name is required.");return}const rows=readDerivedAbilities();const now=new Date().toISOString();let next={...draft,updatedAt:now};if(draft.id){const i=rows.findIndex(a=>a.id===draft.id);if(i<0)return;rows[i]=next}else{const id=rows.reduce((m,a)=>Math.max(m,a.id),0)+1;next={...next,id};rows.push(next)}writeDerivedAbilities(rows);setDraft(next);setDirty(false);setFeedback("Derived Ability saved locally.");setVersion(v=>v+1)}
 function archive(){if(!draft.id)return;const rows=readDerivedAbilities(),i=rows.findIndex(a=>a.id===draft.id);if(i<0)return;const next={...draft,archivedAt:new Date().toISOString(),archiveReason:prompt("Archive reason (optional):")??""};rows[i]=next;writeDerivedAbilities(rows);setDraft(next);setDirty(false);setVersion(v=>v+1)}
 function restore(){if(!draft.id)return;const rows=readDerivedAbilities(),i=rows.findIndex(a=>a.id===draft.id);if(i<0)return;const next={...draft,archivedAt:null,archiveReason:""};rows[i]=next;writeDerivedAbilities(rows);setDraft(next);setDirty(false);setVersion(v=>v+1)}
 function del(){if(!draft.id||prompt("Type "+draft.name+" to delete this local ability:")!==draft.name)return;writeDerivedAbilities(readDerivedAbilities().filter(a=>a.id!==draft.id));setDraft(blankDerivedAbility());setDirty(false);setVersion(v=>v+1)}
 function req():LocalRequirement{return{id:Date.now(),type:"attribute",attributeKey:"STR",skillId:null,derivedAbilityId:null,operator:"gte",value:40,text:"",notes:"",group:1}}
 function cond():LocalCondition{return{id:Date.now(),type:"",comparison:"",numericValue:null,textValue:"",notes:""}}
 function cost():LocalCost{return{id:Date.now(),type:"",amount:null,resourceKey:"",notes:""}}
 function effect():LocalEffect{return{id:Date.now(),effectType:"",amount:null,scope:"",application:"",conditionName:"",description:"",label:"",modifierChannel:"",attributeTarget:"",skillId:null,movementMode:"",target:"",title:"",duration:"",durationCount:null,durationLabel:""}}
 return <main className="skills-page derived-abilities-page">
  <header className="skills-page__header"><div className="skills-page__brand"><Link href="/heavens" className="font-portcullion derived-ability-brand">Serrian<br/>Tide</Link></div><div className="skills-page__title"><p>THE HEAVENS / DERIVED ABILITIES</p><h1>Derived Abilities</h1><span>Local prototype · no database</span></div><div className="skills-page__navigation"><Link href="/heavens">Back to The Heavens</Link></div></header>
  <div className="skills-workspace derived-abilities-workspace">
   <aside className="skill-library"><div className="skill-library__heading"><div><p>MASTER CONTENT</p><h2>Derived Ability Library</h2></div><button className="skills-primary-button" onClick={fresh}>New Ability</button></div><div className="skill-library__search"><label>Search</label><input value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="skill-library__filters derived-ability-library-filters"><label><span>Acquisition</span><select value={acq} onChange={e=>setAcq(e.target.value)}><option value="">All</option><option value="automatic">Automatic</option><option value="purchased">Purchased</option><option value="granted">Granted</option></select></label><label><span>Activation</span><select value={act} onChange={e=>setAct(e.target.value)}><option value="">All</option><option value="passive">Passive</option><option value="active">Active</option><option value="triggered">Triggered</option></select></label></div><div className="skill-library__toolbar"><div className="skill-library__view-toggle"><button className={life==="active"?"is-active":""} onClick={()=>setLife("active")}>Active</button><button className={life==="archived"?"is-active":""} onClick={()=>setLife("archived")}>Archived</button></div><span>{visible.length} abilities</span></div><div className="skill-library__results">{visible.map(a=><button key={a.id} className={"skill-library__row"+(draft.id===a.id?" is-selected":"")} onClick={()=>open(a)}><span className="skill-library__row-name">{a.name}</span>{a.archivedAt?<span className="skill-library__row-status">Archived</span>:null}<span className="derived-ability-library-badges"><em>{a.acquisitionType}</em><em>{a.activationType}</em><em>{a.effects.length} effects</em></span><span className="skill-library__row-meta">{a.requirements.length} requirements · {a.conditions.length} conditions · {a.costs.length} costs</span></button>)}</div></aside>
   <section className="skill-editor derived-ability-editor"><header className="skill-editor__header"><div><p>{draft.id?"DERIVED ABILITY "+draft.id:"NEW DERIVED ABILITY"}</p><h2>{draft.name||"Untitled Ability"}</h2><span>{draft.archivedAt?"Archived":dirty?"Unsaved changes":draft.id?"Saved locally":"Not yet persisted"}</span></div><div className="skill-editor__actions">{draft.id?(draft.archivedAt?<button onClick={restore}>Restore</button>:<button disabled={dirty} onClick={archive}>Archive</button>):null}{draft.id?<button className="skills-danger-button" disabled={dirty} onClick={del}>Delete</button>:null}<button className="skills-primary-button" disabled={Boolean(draft.archivedAt)} onClick={save}>Save Ability</button></div></header>{feedback?<p className="skill-editor__feedback is-success">{feedback}</p>:null}<nav className="skill-editor__tabs">{TABS.map(([id,label])=><button key={id} className={tab===id?"is-active":""} onClick={()=>setTab(id)}>{label}</button>)}</nav>
    <fieldset className="skill-editor__content" disabled={Boolean(draft.archivedAt)}>
     {tab==="definition"?<div className="derived-ability-form-grid"><Field label="Name" wide><input value={draft.name} onChange={e=>change({name:e.target.value})}/></Field><Field label="Description" wide><textarea rows={5} value={draft.description} onChange={e=>change({description:e.target.value})}/></Field><Field label="Acquisition Type"><select value={draft.acquisitionType} onChange={e=>change({acquisitionType:e.target.value})}><option value="automatic">Automatic</option><option value="purchased">Purchased</option><option value="granted">Granted</option></select></Field><Field label="Activation Type"><select value={draft.activationType} onChange={e=>change({activationType:e.target.value})}><option value="passive">Passive</option><option value="active">Active</option><option value="triggered">Triggered</option></select></Field><Field label="Rules Text" wide><textarea rows={8} value={draft.rulesText} onChange={e=>change({rulesText:e.target.value})}/></Field></div>:null}
     {tab==="requirements"?<RepeatSection title="Requirements" add={()=>change({requirements:[...draft.requirements,req()]})}>{draft.requirements.map((r,i)=><article className="derived-ability-edit-row" key={r.id}><header><strong>{r.type}</strong><button className="is-danger" onClick={()=>change({requirements:draft.requirements.filter((_,j)=>j!==i)})}>Remove</button></header><div className="derived-ability-form-grid"><Field label="Requirement Type"><select value={r.type} onChange={e=>change({requirements:draft.requirements.map((x,j)=>j===i?{...x,type:e.target.value as LocalRequirement["type"]}:x)})}><option value="attribute">Attribute</option><option value="skill">Skill</option><option value="derived-ability">Derived Ability</option><option value="manual">Manual</option></select></Field>{r.type==="attribute"?<><Field label="Attribute"><select value={r.attributeKey} onChange={e=>change({requirements:draft.requirements.map((x,j)=>j===i?{...x,attributeKey:e.target.value}:x)})}>{ATTRS.map(a=><option key={a}>{a}</option>)}</select></Field><Field label="Operator"><select value={r.operator} onChange={e=>change({requirements:draft.requirements.map((x,j)=>j===i?{...x,operator:e.target.value}:x)})}><option value="gte">≥</option><option value="gt">&gt;</option><option value="eq">=</option><option value="lte">≤</option></select></Field><Field label="Value"><input type="number" value={r.value??""} onChange={e=>change({requirements:draft.requirements.map((x,j)=>j===i?{...x,value:e.target.value===""?null:Number(e.target.value)}:x)})}/></Field></>:null}{r.type==="skill"?<><Field label="Skill" wide><select value={r.skillId??""} onChange={e=>change({requirements:draft.requirements.map((x,j)=>j===i?{...x,skillId:e.target.value?Number(e.target.value):null}:x)})}><option value="">Choose Skill</option>{skills.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="Required Skill #"><input type="number" value={r.value??""} onChange={e=>change({requirements:draft.requirements.map((x,j)=>j===i?{...x,value:e.target.value===""?null:Number(e.target.value)}:x)})}/></Field></>:null}{r.type==="derived-ability"?<Field label="Derived Ability" wide><select value={r.derivedAbilityId??""} onChange={e=>change({requirements:draft.requirements.map((x,j)=>j===i?{...x,derivedAbilityId:e.target.value?Number(e.target.value):null}:x)})}><option value="">Choose Derived Ability</option>{abilities.filter(a=>a.id!==draft.id&&!a.archivedAt).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field>:null}{r.type==="manual"?<Field label="Requirement Text" wide><textarea rows={3} value={r.text} onChange={e=>change({requirements:draft.requirements.map((x,j)=>j===i?{...x,text:e.target.value}:x)})}/></Field>:null}<Field label="Notes" wide><textarea rows={2} value={r.notes} onChange={e=>change({requirements:draft.requirements.map((x,j)=>j===i?{...x,notes:e.target.value}:x)})}/></Field></div></article>)}</RepeatSection>:null}
     {tab==="conditions"?<RepeatSection title="Use Conditions" add={()=>change({conditions:[...draft.conditions,cond()]})}>{draft.conditions.map((r,i)=><article className="derived-ability-edit-row" key={r.id}><header><strong>{r.type||"Condition"}</strong><button className="is-danger" onClick={()=>change({conditions:draft.conditions.filter((_,j)=>j!==i)})}>Remove</button></header><div className="derived-ability-form-grid"><Field label="Condition Type"><input value={r.type} onChange={e=>change({conditions:draft.conditions.map((x,j)=>j===i?{...x,type:e.target.value}:x)})}/></Field><Field label="Comparison"><input value={r.comparison} onChange={e=>change({conditions:draft.conditions.map((x,j)=>j===i?{...x,comparison:e.target.value}:x)})}/></Field><Field label="Numeric Value"><input type="number" value={r.numericValue??""} onChange={e=>change({conditions:draft.conditions.map((x,j)=>j===i?{...x,numericValue:e.target.value===""?null:Number(e.target.value)}:x)})}/></Field><Field label="Text Value"><input value={r.textValue} onChange={e=>change({conditions:draft.conditions.map((x,j)=>j===i?{...x,textValue:e.target.value}:x)})}/></Field><Field label="Notes" wide><textarea value={r.notes} onChange={e=>change({conditions:draft.conditions.map((x,j)=>j===i?{...x,notes:e.target.value}:x)})}/></Field></div></article>)}</RepeatSection>:null}
     {tab==="costs"?<RepeatSection title="Costs" add={()=>change({costs:[...draft.costs,cost()]})}>{draft.costs.map((r,i)=><article className="derived-ability-edit-row" key={r.id}><header><strong>{r.type||"Cost"}</strong><button className="is-danger" onClick={()=>change({costs:draft.costs.filter((_,j)=>j!==i)})}>Remove</button></header><div className="derived-ability-form-grid"><Field label="Cost Type"><input value={r.type} onChange={e=>change({costs:draft.costs.map((x,j)=>j===i?{...x,type:e.target.value}:x)})}/></Field><Field label="Amount"><input type="number" value={r.amount??""} onChange={e=>change({costs:draft.costs.map((x,j)=>j===i?{...x,amount:e.target.value===""?null:Number(e.target.value)}:x)})}/></Field><Field label="Resource Key"><input value={r.resourceKey} onChange={e=>change({costs:draft.costs.map((x,j)=>j===i?{...x,resourceKey:e.target.value}:x)})}/></Field><Field label="Notes" wide><textarea value={r.notes} onChange={e=>change({costs:draft.costs.map((x,j)=>j===i?{...x,notes:e.target.value}:x)})}/></Field></div></article>)}</RepeatSection>:null}
     {tab==="limits"?<div className="derived-ability-form-grid"><Field label="Maximum Uses"><input type="number" value={draft.limit.maximumUses??""} onChange={e=>change({limit:{...draft.limit,maximumUses:e.target.value===""?null:Number(e.target.value)}})}/></Field><Field label="Refresh Scope"><input value={draft.limit.refreshScope} onChange={e=>change({limit:{...draft.limit,refreshScope:e.target.value}})}/></Field><Field label="Refresh Event Key"><input value={draft.limit.refreshEventKey} onChange={e=>change({limit:{...draft.limit,refreshEventKey:e.target.value}})}/></Field><Field label="Notes" wide><textarea rows={4} value={draft.limit.notes} onChange={e=>change({limit:{...draft.limit,notes:e.target.value}})}/></Field></div>:null}
     {tab==="effects"?<RepeatSection title="Mechanical Effects" add={()=>change({effects:[...draft.effects,effect()]})}>{draft.effects.map((r,i)=><article className="derived-ability-edit-row" key={r.id}><header><strong>{r.title||r.effectType||"Effect"}</strong><button className="is-danger" onClick={()=>change({effects:draft.effects.filter((_,j)=>j!==i)})}>Remove</button></header><div className="derived-ability-form-grid">{[["effectType","Effect Type"],["scope","Scope"],["application","Application"],["conditionName","Condition Name"],["label","Label"],["modifierChannel","Modifier Channel"],["attributeTarget","Attribute Target"],["movementMode","Movement Mode"],["target","Target"],["title","Title"],["duration","Duration"],["durationLabel","Duration Label"]].map(([k,l])=><Field key={k} label={l}><input value={String(r[k as keyof LocalEffect]??"")} onChange={e=>change({effects:draft.effects.map((x,j)=>j===i?{...x,[k]:e.target.value}:x)})}/></Field>)}<Field label="Amount"><input type="number" value={r.amount??""} onChange={e=>change({effects:draft.effects.map((x,j)=>j===i?{...x,amount:e.target.value===""?null:Number(e.target.value)}:x)})}/></Field><Field label="Duration Count"><input type="number" value={r.durationCount??""} onChange={e=>change({effects:draft.effects.map((x,j)=>j===i?{...x,durationCount:e.target.value===""?null:Number(e.target.value)}:x)})}/></Field><Field label="Skill Target"><select value={r.skillId??""} onChange={e=>change({effects:draft.effects.map((x,j)=>j===i?{...x,skillId:e.target.value?Number(e.target.value):null}:x)})}><option value="">None</option>{skills.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="Description" wide><textarea rows={3} value={r.description} onChange={e=>change({effects:draft.effects.map((x,j)=>j===i?{...x,description:e.target.value}:x)})}/></Field></div></article>)}</RepeatSection>:null}
     {tab==="preview"?<article className="derived-preview"><header><p>{draft.acquisitionType} · {draft.activationType}</p><h3>{draft.name||"Untitled Ability"}</h3></header><p>{draft.description||"No description."}</p><section><h4>Rules</h4><p>{draft.rulesText||"No Rules Text."}</p></section><div className="derived-ability-library-badges"><em>{draft.requirements.length} requirements</em><em>{draft.conditions.length} conditions</em><em>{draft.costs.length} costs</em><em>{draft.effects.length} effects</em></div></article>:null}
    </fieldset>
   </section>
  </div>
 </main>
}
function RepeatSection({title,add,children}:{title:string;add:()=>void;children:React.ReactNode}){return <div className="local-derived-repeat"><header><h3>{title}</h3><button onClick={add}>Add</button></header><div>{children}</div></div>}
