"use client";
import { useMemo,useState } from "react";
import styles from "./appearance.module.css";
const KEY="serrian-tide:prototype:appearance:v1";
const defaults={pageBackground:"#04030C",surfaceBackground:"#0B1018",primaryAccent:"#9C63D9",secondaryAccent:"#E5BD5A",mainText:"#EFE9DA",mutedText:"#94A3B8"};
type Theme=typeof defaults;
function read():Theme{if(typeof window==="undefined")return defaults;try{return{...defaults,...JSON.parse(localStorage.getItem(KEY)??"{}")}}catch{return defaults}}
function apply(t:Theme){document.documentElement.style.setProperty("--st-page",t.pageBackground);document.documentElement.style.setProperty("--st-surface",t.surfaceBackground);document.documentElement.style.setProperty("--st-primary",t.primaryAccent);document.documentElement.style.setProperty("--st-secondary",t.secondaryAccent);document.documentElement.style.setProperty("--st-text",t.mainText);document.documentElement.style.setProperty("--st-muted",t.mutedText)}
const labels:{[K in keyof Theme]:string}={pageBackground:"Page background",surfaceBackground:"Panel / surface background",primaryAccent:"Primary accent",secondaryAccent:"Secondary accent",mainText:"Main text",mutedText:"Muted text"};
export function LocalAppearanceWorkspace(){
 const [saved,setSaved]=useState<Theme>(()=>read());const [draft,setDraft]=useState<Theme>(()=>read());const changed=useMemo(()=>JSON.stringify(saved)!==JSON.stringify(draft),[saved,draft]);
 function save(){localStorage.setItem(KEY,JSON.stringify(draft));setSaved(draft);apply(draft)}
 function reset(){setDraft(defaults)}
 return <div className={styles.workspace}><section className={styles.controls}><div><p className={styles.eyebrow}>Theme controls</p><h2>Colors</h2></div><div className={styles.colorGrid}>{(Object.keys(draft) as Array<keyof Theme>).map(field=><label key={field} className={styles.colorField}><span>{labels[field]}</span><span className={styles.colorInputs}><input type="color" value={draft[field]} onChange={e=>setDraft({...draft,[field]:e.target.value.toUpperCase()})}/><input value={draft[field]} onChange={e=>setDraft({...draft,[field]:e.target.value.toUpperCase()})}/></span></label>)}</div><div className={styles.actions}><button className={styles.primaryAction} disabled={!changed} onClick={save}>Save appearance locally</button><button disabled={!changed} onClick={()=>setDraft(saved)}>Cancel changes</button><button onClick={reset}>Restore preset defaults</button></div></section><section className={styles.previewSection}><div className={styles.previewHeading}><div><p className={styles.eyebrow}>Unsaved draft</p><h2>Immediate preview</h2></div><span>{changed?"Not yet saved":"Matches local site"}</span></div><div className={styles.preview} style={{"--st-page":draft.pageBackground,"--st-surface":draft.surfaceBackground,"--st-primary":draft.primaryAccent,"--st-secondary":draft.secondaryAccent,"--st-text":draft.mainText,"--st-muted":draft.mutedText} as React.CSSProperties}><nav><strong className="font-portcullion">Serrian Tide</strong><span>Heavens</span><span>Realms</span><span>Crossroads</span></nav><article><p>PREVIEW CARD</p><h3>Readable theme sample</h3><p>This preview changes without a database.</p><label>Example input<input defaultValue="Serrian Tide"/></label><div><button>Primary</button><button>Secondary</button></div></article></div></section></div>;
}
